### ISSUE TITLE
Fiber not found - Ubuntu 20.04 - Node 16 - Yarn

### ISSUE THREAD

**Issue by JorgeSivil** [joshwcomeau/react-flip-move#262]
I wanted to use this library but sadly I wasn't able to even make my project compile. Looks like the Fibers thing is difficult to install. I don't want to install gcc etc in my docker image.
I'm sad that there's no way to not use this. 

```
/usr/local/bin/node /home/jorgee/Desktop/Proyectos/ranking/ranking-v3/node_modules/next/dist/bin/next
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from /home/jorgee/Desktop/Proyectos/ranking/ranking-v3/.env.local
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
Using APP_ENV="local"
## There is an issue with `node-fibers` ##
`/home/jorgee/Desktop/Proyectos/ranking/ranking-v3/node_modules/fibers/bin/linux-x64-88-glibc/fibers.node` is missing.

Try running this to fix the issue: /usr/local/bin/node /home/jorgee/Desktop/Proyectos/ranking/ranking-v3/node_modules/fibers/build
Error: Cannot find module '/home/jorgee/Desktop/Proyectos/ranking/ranking-v3/node_modules/fibers/bin/linux-x64-88-glibc/fibers'
Require stack:
- /home/jorgee/Desktop/Proyectos/ranking/ranking-v3/node_modules/fibers/fibers.js
- /home/jorgee/Desktop/Proyectos/ranking/ranking-v3/node_modules/next/dist/compiled/sass-loader/cjs.js
- /home/jorgee/Desktop/Proyectos/ranking/ranking-v3/node_modules/next/dist/compiled/webpack/bundle5.js
- /home/jorgee/Desktop/Proyectos/ranking/ranking-v3/node_modules/next/dist/compiled/webpack/webpack.js
- /home/jorgee/Desktop/Proyectos/ranking/ranking-v3/node_modules/next/dist/next-server/server/config-utils-worker.js
- /home/jorgee/Desktop/Proyectos/ranking/ranking-v3/node_modules/next/dist/next-server/server/config-utils.js
- /home/jorgee/Desktop/Proyectos/ranking/ranking-v3/node_modules/next/dist/next-server/server/config.js
- /home/jorgee/Desktop/Proyectos/ranking/ranking-v3/node_modules/next/dist/server/next.js
- /home/jorgee/Desktop/Proyectos/ranking/ranking-v3/node_modules/next/dist/server/lib/start-server.js
- /home/jorgee/Desktop/Proyectos/ranking/ranking-v3/node_modules/next/dist/cli/next-dev.js
- /home/jorgee/Desktop/Proyectos/ranking/ranking-v3/node_modules/next/dist/bin/next
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)
    at Function.mod._resolveFilename (/home/jorgee/Desktop/Proyectos/ranking/ranking-v3/node_modules/next/dist/build/webpack/require-hook.js:4:1855)
    at Function.Module._load (node:internal/modules/cjs/loader:769:27)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/home/jorgee/Desktop/Proyectos/ranking/ranking-v3/node_modules/fibers/fibers.js:14:39)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
## There is an issue with `node-fibers` ##
`/home/jorgee/Desktop/Proyectos/ranking/ranking-v3/node_modules/fibers/bin/linux-x64-88-glibc/fibers.node` is missing.

```

Node v16.4.2

Now I reverted package.json and yarn.lock and ran yarn install but I still get the same error.
I deleted Yarn cache directory, node_modules and .next directories. Still all broken.

**Comment by JorgeSivil** [comment]
It solved by using node 12.14.1
